OnePassword/OnePassword/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("onepass.urls"))
]

OnePassword/onepass/urls.py
from django.urls import path
from . import views

# app_name
app_name = "onepass"

# Url Patterns
urlpatterns = [path("", views.index, name="index"),
               path("login_page", views.login_page, name="login_page"),
               path("signup_page", views.signup_page, name="signup_page"),
               path("dashboard", views.dashboard, name="dashboard")]

OnePassword/onepass/models.py
from django.db import models

# Create your models here.
class onepass_users(models.Model):
    user_name = models.CharField(max_length=64)
    password = models.CharField(max_length=64)

    def __str__(self):
        return f"user_name = {self.user_name} and password = {self.password}"

class onepass_text(models.Model):
    user_name = models.CharField(max_length=64, default="<user_name>")
    user_data = models.TextField(default="<user_data>")
    def __str__(self):
        return f"user_data = {self.user_data}"

OnePassword/onepass/views.py
from django.shortcuts import render
from .models import onepass_users, onepass_text

# Create your views here.
def index(request):
    return render(request, "onepass/index.html")

def login_page(request):
    if request.method == "POST":
        try:
            user_name = request.POST.get("user_name")
            password = request.POST.get("password")
            user = onepass_users.objects.get(user_name=user_name)
            if user.password == password:
                user_entries = onepass_text.objects.filter(user_name=user_name)
                user_text = [entry.user_data for entry in user_entries]
                return render(request, "onepass/dashboard.html", {"user_name" : user_name, "user_text" : user_text})
            else:
                return render(request, "onepass/login_page.html")
        except onepass_users.DoesNotExist:
            return render(request, "onepass/login_page.html")
    return render(request, "onepass/login_page.html")

def dashboard(request):
    if request.method == "POST":
        user_name = request.POST.get("user_name")
        pre_text = request.POST.get("previous_text")
        user_text = request.POST.get("text")
        new_entry = onepass_text(user_name=user_name, user_data=user_text)
        new_entry.save()
        user_entries = onepass_text.objects.filter(user_name=user_name)
        user_text = [entry.user_data for entry in user_entries]
    return render(request, "onepass/dashboard.html", {"user_name" : user_name, "user_text" : user_text})
    
def signup_page(request):
    if request.method == "POST":
        user_name = request.POST.get("user_name")
        password = request.POST.get("password")
        new_user = onepass_users(user_name=user_name, password=password)
        new_user.save()
        return render(request, "onepass/login_page.html")
    # elif request.method == "GET":
    return render(request, "onepass/signup_page.html")

OnePassword/onepass/templates/onepass/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>One Password</title>
</head>
<body>
    <h1>Dash Board</h1>
    {{ user_name }}
    <form action="{% url 'onepass:dashboard' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="user_name" value="{{user_name}}">
        <input type="hidden" name="previous_text" value="{{user_text}}">
        {{user_text}}
        <br>
        <textarea name="text" placeholder="" rows="4" cols="50"></textarea>
        <br>
        <button type="submit">Add</button>
    </form>
</body>
</html>

OnePassword/onepass/templates/onepass/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>One Password</title>
</head>
<body>
    <h1>One Password</h1>
    <form action="{% url 'onepass:login_page' %}" method="get">
        {% csrf_token %}
        <button type="submit">Log In</button>
    </form>
    <form action="{% url 'onepass:signup_page' %}" method="get">
        {% csrf_token %}
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>

OnePassword/onepass/templates/onepass/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>One Password</title>
</head>
<body>
    <h1>Login</h1>
    <form action="{% url 'onepass:login_page' %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="username" name="user_name">
        <br>
        <input type="password" placeholder="password" name="password">
        <br>
        <button type="submit">Click</button>
    </form>
</body>
</html>

OnePassword/onepass/templates/onepass/signup_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>One Password</title>
</head>
<body>
    <h1>SignUp_page</h1>
    <form action="{% url 'onepass:signup_page' %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="username" name="user_name">
        <br>
        <input type="password" placeholder="password" name="password">
        <br>
        <button type="submit">Click</button>
    </form>
</body>
</html>